apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind * -::*
    protected-mode no
    maxmemory 4g
    maxmemory-policy allkeys-lru
    maxmemory-samples 5
    lazyfree-lazy-eviction no
    lazyfree-lazy-expire no
    lazyfree-lazy-server-del no
    slave-lazy-flush no
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 75
    auto-aof-rewrite-min-size 128mb
    tls-port 6379
    port 0
    tls-cert-file /etc/tls/redis.crt
    tls-key-file /etc/tls/redis.key
    tls-ca-cert-file /etc/tls/rootca.crt
    tls-auth-clients no
    tls-replication yes
    replica-read-only yes