apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-service
  labels:
    tier: database
    app: redis-sentinel
spec:
  selector:
    tier: database
    app: redis-sentinel
    role: sentinel
  ports:
    - name: redis-sentinel-port
      protocol: TCP
      port: 26379
      targetPort: 26379
  type: LoadBalancer