apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc-deployment
  labels:
    tier: app
    app: dc
spec:
  selector:
    matchLabels:
      tier: app
      app: dc
  replicas: 1
  template:
    metadata:
      labels:
        tier: app
        app: dc
    spec:
      containers:
        - name: dc
          image: hgbdev/dc:0.0.1
          imagePullPolicy: Always
          env:
            - name: CONF_FILE
              valueFrom:
                configMapKeyRef:
                  name: dc-config
                  key: CONF_FILE
            - name: APITEST_PORT
              valueFrom:
                configMapKeyRef:
                  name: dc-config
                  key: APITEST_PORT
          ports:
            - name: dc-socket-port
              containerPort: 19999
            - name: dc-apitest-port
              containerPort: 8000
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: dc-config-volume
              mountPath: /home/hgb/conf.d/config.conf
              subPath: config.conf
            - name: embulk-volume
              mountPath: /home/hgb/embulk
            - name: embulk-data-volume
              mountPath: /data
      imagePullSecrets:
        - name: dc-imagepull-secret
      volumes:
        - name: dc-config-volume
          configMap:
            name: dc-config
            items:
              - key: config.conf
                path: config.conf
        - name: embulk-volume
          persistentVolumeClaim:
            claimName: dc-embulk-pvc
        - name: embulk-data-volume
          persistentVolumeClaim:
            claimName: dc-embulk-data-pvc
