apiVersion: v1
kind: Service
metadata:
  name: apitest-service
spec:
  selector:
    tier: app
    app: dc
  ports:
    - name: apitest-port
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer