apiVersion: v1
kind: Service
metadata:
  name: dc-service
spec:
  selector:
    tier: storage
    app: minio
  ports:
    - name: console-ui
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer